version: 2
updates:
  - directory: /
    package-ecosystem: bundler
    rebase-strategy: auto
    schedule:
      interval: daily
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
