---
name: Rails CI
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
env:
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
  rspec:
    runs-on: ubuntu-latest
    needs: bundle
    env:
      PGHOST: localhost
      PGUSER: deckshare
      PGPASSWORD: deckshare
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_DB: deckshare_test
          POSTGRES_PASSWORD: deckshare
          POSTGRES_USER: deckshare
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/rails db:setup
      - uses: actions/cache@v4
        id: asset_cache
        with:
          path: public/assets/
          key: assets-${{ hashFiles('app/assets/**') }}
          restore-keys: |
            assets-
      - run: bin/rails assets:precompile
      - run: bin/rspec
